config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :wheelies do
    resources :bookings, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :wheely
  belongs_to :user

  validates :booking_date, presence: true
  validates :wheely_id, presence: true
  validates_uniqueness_of :booking_date, scope: [:wheely_id]
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :wheelies
  has_many :bookings
end

app/models/wheely.rb
class Wheely < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :bookings

  validates :address, presence: true
  validates :description, presence: true
  validates :category_id, presence: true
  validates :user, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  mount_uploader :photo, PhotoUploader
  include PgSearch
  pg_search_scope :global_search,
    associated_against: {
      category: :name
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @wheely = Wheely.find(params[:wheely_id])
    authorize(@wheely)
    @booking = @wheely.bookings.new
  end

  def create
    @wheely = Wheely.find(params[:wheely_id])
    authorize(@wheely)
    @booking = @wheely.bookings.new(booking_params)
    @booking.user = current_user
    if @booking.save
      redirect_to wheely_path(@wheely)
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:booking_date, :wheely_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @wheelies = policy_scope(Wheely).order(created_at: :desc)
  end
end

app/controllers/wheelies_controller.rb
class WheeliesController < ApplicationController
  before_action :set_wheely, only: [:show, :edit, :update, :destroy]

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      if params[:query] == "All"
        @wheelies = policy_scope(Wheely).order(created_at: :desc).near("#{params[:location]}", 1)
      else
        @wheelies = policy_scope(Wheely).global_search("#{params[:query]}").near("#{params[:location]}", 1)
      end
    else
      @wheelies = policy_scope(Wheely).order(created_at: :desc)
    end
    @wheelies_geo = @wheelies.select{ |wheely| !wheely.latitude.nil? && !wheely.longitude.nil?}

    @markers = @wheelies_geo.map do |wheely|
      {
        lat: wheely.latitude,
        lng: wheely.longitude,
        infoWindow: { content: render_to_string(partial: "/wheelies/map_box", locals: { wheely: wheely }) }
      }
    end

  end

  def show
    # @wheelies_geo = @wheelies.select{ |wheely| !wheely.latitude.nil? && !wheely.longitude.nil?}
    @marker = [{
        lat: @wheely.latitude,
        lng: @wheely.longitude#,
        # infoWindow: { content: render_to_string(partial: "/wheelies/map_box", locals: { wheely: wheely }) }
      }]
  end

  def new
    @wheely = Wheely.new
    authorize(@wheely)
  end

  def create
    @wheely = Wheely.new(wheely_params)
    authorize(@wheely)
    @wheely.user = current_user

    if @wheely.save
      redirect_to @wheely, notice: 'Wheely was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @wheely.update(wheely_params)
      redirect_to @wheely, notice: 'Wheely was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @wheely.destroy
    redirect_to wheelies_path, notice: 'Wheely was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_wheely
    @wheely = Wheely.find(params[:id])
    authorize(@wheely)
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def wheely_params
    params.require(:wheely).permit(:title, :address, :description, :price, :user_id, :category_id, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="card-form">

          <h1>Book a Wheely</h1>
            <h2><%= @wheely.title %></h2>
            <h3><%= @wheely.price%> €/jr </h3>

            <%= simple_form_for [@wheely, @booking], html: { class: 'form-horizontal' } do |f| %>
              <%= f.error_notification %>

              <div class="form-inputs">
                <%= f.input :booking_date, as: :string %>
              </div>

              <div class="form-actions">
                <%= link_to 'Cancel', :back, class: "btn btn-default"%>
                <%= f.button :submit, 'Book', class: "btn btn-success pull-right" %>
              </div>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="banner-form" style="background-image: linear-gradient(-225deg, rgba(86,101,89,0.3) 0%, rgba(25,36,61,0.4) 50%), url(<%= asset_path 'home.jpg' %>);">
  <%= render 'form', wheely: @wheely %>
</div>


<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button> -->

<!-- Modal -->
<!-- <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="booking-box" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="form-actions">
        <button type="button" class="form-actions" data-dismiss="modal">submit</button>
        <button type="button" class="form-actions">Canceled</button>
      </div>
    </div>
  </div>
</div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>WheelIn - What wheeler ar you?</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'components/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'components/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(86,101,89,0.3) 0%, rgba(25,36,61,0.4) 50%), url(<%= asset_path 'home.jpg' %>);">
  <div class="banner-content">
    <h1>WheelIn</h1>
    <p>What kind of wheeler are you?</p>
    <form action="<%= wheelies_path %>" method="get">
      <div class="form-group">
        <label class="control-label" for="query">Category</label>
        <select class="form-control" name="query" id="search_home">
          <!-- <option value="" disabled selected>Category</option> -->
          <option> All </option>
          <% Category.all.each do |category| %>
            <option><%= category.name %></option>
          <% end %>
        </select>
      </div>
      <div class="form-group">
        <label class="control-label" for="location">Where?</label>
        <input id="wheely_address" class="form-control" type="text" name="location" placeholder="Search for a place" value="<%= params[:location] %>">
      </div>
      <input class="btn btn-success" type="submit" value="Search">
    </form>
  </div>
</div>


<div class="container">
  <h2 class="text-center">Try one of our wheelies!</h2>
  <div class="row">
    <% @wheelies.each do |wheely| %>
        <div class="col-xs-12 col-sm-4 col-md-3 wheely_card">
          <%= render 'shared/card', wheely: wheely  %>
        </div>
      </a>
    <% end%>
  </div>
</div>

app/views/shared/_card.html.erb
<%= link_to(wheely_path(wheely)) do %>
  <div class="wheely_card_body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= wheely.photo %>);">
    <span class="price"><%= wheely.price %>€ / jour</span>
  </div>
  <div class="wheely_card_footer">
    <div class="wheely_card_title"><%= wheely.title %></div>
    <img src="https://www.w3schools.com/w3images/avatar2.png" alt="" class="wheely_card_avatar">
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/wheelies/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="card-form">
        <h1>Add a new Wheely</h1>
        <%= simple_form_for(@wheely) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= f.input :title %>
            <%= f.association :category, include_blank: false %>
            <%= f.input :address%>
            <%= f.input :description %>
            <%= f.input :price, label: 'Price (€ / jr)' %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
          </div>

          <div class="form-actions">
            <%= link_to 'Cancel', :back, class: "btn btn-default"%>
            <%= f.button :submit, 'Post my wheely', class: "btn btn-success pull-right" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/wheelies/_map_box.html.erb
<p><%= wheely.title %></p>
<p><%= wheely.address %></p>

app/views/wheelies/edit.html.erb
<h1>Edit <%= @wheely.title %></h1>

<%= render 'form', wheely: @wheely %>

<%= link_to 'Back to Wheelies', :back %>

app/views/wheelies/index.html.erb
<div class="flex-container">
  <div class="wheelies">
    <form action="<%= wheelies_path %>" method="get" class="form-inline">
      <div class="form-row">
        <div class="form-group col">
            <!-- <label class="control-label" for="query">Category</label> -->
          <select class="form-control" name="query" id="search_home" value= "<%= params[:query] %>">
            <option>
              <% if params[:query].nil? %>
                All
              <% else %>
                <%= params[:query] %>
              <% end %>
            </option>
            <% Category.all.each do |category| %>
              <option><%= category.name %></option>
            <% end %>
          </select>
        </div>
        <div class="form-group col">
          <!-- <label class="control-label" for="location">Where?</label> -->
          <input class="form-control" type="text" name="location" placeholder="Search for a place" value="<%= params[:location] %>">
        </div>
        <div class="form-group col">
          <input class="btn btn-success" type="submit" value="Search">
        </div>
      </div>
    </form>
    <div class="row">
      <% @wheelies.each do |wheely| %>
        <div class="col-xs-12 col-sm-6 col-md-4 wheely_card">
          <%= render '/shared/card', wheely: wheely  %>
        </div>
      <% end%>
    </div>
  </div>
  <div
    id="map"
    data-markers="<%= @markers.to_json %>">
  </div>
</div>

app/views/wheelies/new.html.erb
<div class="banner-form" style="background-image: linear-gradient(-225deg, rgba(86,101,89,0.3) 0%, rgba(25,36,61,0.4) 50%), url(<%= asset_path 'home.jpg' %>);">
  <%= render 'form', wheely: @wheely %>
</div>

app/views/wheelies/search.html.erb
<h1>Our Wheelies</h1>

<div class="container">
  <div class="row">
    <% @wheelies.each do |wheely| %>
      <div class="col-xs-12 col-sm-4 col-md-3">
        <%= link_to(wheely_path(wheely), class: "card") do %>
          <h2> <%= wheely.title %></h2>
          <p> <%= wheely.description %></p>
          <p> <%= wheely.price %> <i class="fas fa-euro-sign"></i></p>
          <%= cl_image_tag wheely.photo, height: 300, width: 400, crop: :fill %>
        <% end %>
      </div>
    <% end%>
  </div>
</div>

<%= link_to "add a new wheely",  new_wheely_path %>

app/views/wheelies/show.html.erb
<div class="wheely-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= @wheely.photo %>);">
</div>
<%= link_to '< Back to Wheelies', wheelies_path, class: "btn-back" %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="ad-box">
        <h3>Category > <%= @wheely.category.name %></h3>
        <h1> <%= @wheely.title %></h1>
        <p> <%= @wheely.description %></p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="map-booking-box">
        <div
          id="map"
          style="width: 100%;
          height: 250px;"
          data-markers="<%= @marker.to_json %>"
        ></div>
        <div class="row">
          <div class="col-xs-6">
            <div id="price-booking">
            <p> <%= @wheely.price %> € / jr </i></p>
            </div>
          </div>
          <div class="col-xs-6">
            <div id="btn-booking">
              <%= link_to 'Book this wheely !', new_wheely_booking_path(@wheely.id), class: "btn btn-success" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<% if policy(@wheely).update? %>
  <%= link_to 'Edit', edit_wheely_path(@wheely) %> <br>
<% end %>
<% if policy(@wheely).destroy? %>
  <%= link_to "Delete", wheely_path(@wheely),
      method: :delete,
      data: { confirm: "Are you sure?" } %> <br>
<% end %>